language: python
python:
  - "3.4"
# command to install dependencies
virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python3-dev python3-numpy
  - sudo apt-get install python3-dev python3-scipy

install: 
 - "pip install -r requirements.txt"

# command to run tests
script: nosetests 

