
language: python
python:
  - "3.4"
notifications:
  email: false
services:
  - docker

# Setup anaconda
before_install:
  # Steps for installing Miniconda adapted from
  # http://conda.pydata.org/docs/travis.html
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  - git clone https://github.com/anderspitman/tidepool-docker
  - tidepool-docker/build_containers tidepool-docker anderspitman
  - tidepool-docker/start_containers tidepool-docker anderspitman
# Install packages
install:
  - conda install python=$TRAVIS_PYTHON_VERSION pip numpy pandas nose scipy six patsy python-dateutil statsmodels pytz pymongo requests
  - pip install chai
  - pip install rednose

# Run test
script:
  - "nosetests -v --rednose"
  - python dfaker_cli.py -n 2 -f upload_data.json
  - python upload.py
