
language: python
python:
  - "3.4"
notifications:
  email: false
services:
  - docker

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  - git clone https://github.com/anderspitman/tidepool-docker
  - tidepool-docker/build_containers tidepool-docker anderspitman
  - tidepool-docker/start_containers tidepool-docker anderspitman
# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy pandas nose scipy six patsy python-dateutil statsmodels pytz pymongo requests
  - pip install chai
  - pip install rednose

# Run test
script:
  - "nosetests -v --rednose"
  - python dfaker_cli.py -n 2
  - python upload.py
