language: python
python:
  - "3.4_with_system_site_packages"

before_install:
 - sudo apt-get update
 - sudo apt-get install python-opencv

install: 
 - "pip install -r requirements.txt"

# command to run tests
script: nosetests 

